groups: []

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: goblob
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:pivotalservices/goblob.git

- name: goblob-rc
  type: gcs-resource
  source:
    bucket: goblob-releases
    json_key: {{gcs-private-key}}
    regexp: rc/goblob-(.*).tgz

- name: goblob-gcs-release
  type: gcs-resource
  source:
    bucket: goblob-releases
    json_key: {{gcs-private-key}}
    regexp: final/goblob-(.*).tgz

- name: goblob-gh-release
  type: github-release
  source:
    drafts: false
    user: pivotalservices
    repository: goblob
    access_token: {{github-access-token}}

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:pivotalservices/goblob.git
    branch: version
    file: version
    private_key: {{git-private-key}}

jobs:
- name: create-rc
  serial_groups: [version]
  plan:
  - aggregate:
    - get: goblob
      trigger: true
    - get: version
      params: {pre: rc}
  - task: install-dependencies
    file: goblob/ci/install-dependencies.yml
  - aggregate:
    - task: unit
      file: goblob/ci/unit.yml
      params:
        MINIO_ACCESS_KEY: example-access-key
        MINIO_SECRET_KEY: example-secret-key
    - task: build
      file: goblob/ci/build.yml
  - aggregate:
    - put: version
      params: {pre: rc}
    - put: goblob-rc
      params:
        file: tarball/goblob-*.tgz

- name: shipit
  serial_groups: [version]
  plan:
  - aggregate:
    - get: goblob-rc
      passed: [create-rc]
    - get: version
      params: {bump: final}
    - get: goblob
      passed: [create-rc]
  - task: create-release-notes
    file: goblob/ci/create-release-notes.yml
  - put: goblob
    params:
      repository: goblob
      only_tag: true
      tag: version/version
      tag_prefix: v
  - put: version
    params:
      bump: minor
      pre: rc
  - aggregate:
    - put: goblob-gcs-release
      params:
        file: goblob-rc/goblob-*.tgz
    - put: goblob-gh-release
      params:
        name: version/version
        tag: version/version
        tag_prefix: v
        globs:
        - goblob-rc/goblob-**.tgz
